#cloud-config
package_update: true

manage-resolv-conf: true

resolv_conf:
  nameservers:
    - '8.8.8.8'

packages:
  - curl

runcmd:
  - bash -c "$(curl -fsSL https://gist.github.com/tuyendev/3a3bca421b6689f73c670257090b5d34/raw/c31f3de439c5ac86c4e4c7b50bf95a26988b0bd5/nomad-consul-prerequisite.sh)"
  - bash -c "$(curl -fsSL https://gist.github.com/tuyendev/63a0a75c1abd354199fd12ef04bacafe/raw/71c7f72cc21943fd8679ad148c4494a55f627dc9/consul-nomad-install.sh)"
  - usermod -aG docker ubuntu
final_message: "Ready to Dock!"
